name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5
      - uses: ./
        id: upload
        env:
          MODIO_DEBUG_OVERRIDE_URL: https://httpbin.org/post
        with:
          token: foobar
          game: 123
          mod: 456
          path: action.yml

          version: '1.0'
          changelog-path: README.md
          metadata: '{"foo":"bar"}'

      - run: |
          : echo output
          echo "${{ steps.upload.outputs.response }}"
          cat "${{ steps.upload.outputs.response }}"
        shell: bash

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@shellcheck
      - uses: taiki-e/install-action@shfmt
      - run: yarn add prettier
      - run: shfmt -d $(git ls-files '*.sh')
        if: always()
      - run: yarn run prettier -c $(git ls-files '*.yml')
        if: always()
      - run: shellcheck $(git ls-files '*.sh')
        if: always()
